version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: jojo_admin
      POSTGRES_PASSWORD: star_platinum
      POSTGRES_DB: stand_pedia_db
    ports:
      - "5432:5432"